image:
  repository: proget.mattgerega.com/spydersoft/ha/unifi.client
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

imagePullSecrets: 
  - name: spydersoft-proget

secret:
  ConnectionStrings__MainsiteConnection: "<your_connection>"

env:
  Identity__ApiName: "unifi.client"

## The "standard-net-environment" ConfigMap is a list of standard environmental variables ,
##  that are unique to the namespace (test/stage/prod).
envFrom: 
  - configMapRef:
      name: standard-net-environment

service:
  port:
    port: 80
    targetPort: 8080

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  labels: 
    ingressClassName: "nginx"
  hosts:
    - host: test.mattgerega.net
      paths:
        - path: /
          pathType: Prefix