resources:
  repositories:
    - repository: templates
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/azure-devops-templates
    - repository: helmfileconfig
      type: github
      endpoint: spydersoft-gh
      name: spyder007/ha-helm-config

variables:
  #- group: confluence-credentials
  - name: CI
    value: true
  - name: artifactName
    value: unifi-client
  - name: dockerRepository
    value: spydersoft/ha/unifi.client
  - name: dockerServiceConnection
    value: proget_docker
  - name: branchTag
    ${{ if contains(variables['Build.SourceBranch'], 'main') }}:
      value: main
    ${{ if not(contains(variables['Build.SourceBranch'], 'main')) }}:
      value: feature

trigger:
  - main
  - feature/*
pr: none

stages:
  - stage: build
    jobs:
      - job: buildJob
        pool:
          name: Default
        steps:
          - template: step_collections/yarn-build-test.yml@templates
            parameters:
              artifactName: $(artifactName)
              runTests: true
              zipBuildArtifacts: true

  - stage: docker_publish
    displayName: Create Container and Publish
    dependsOn: build
    jobs:
      - template: jobs/docker-image-job.yml@templates
        parameters:
          dockerImageName: $(dockerRepository)
          containerRegistryName: proget_docker
          artifactName: $(artifactName)
          artifactZipName: $(artifactName)
          dockerFilePath: $(Build.SourcesDirectory)/Dockerfile
          artifactTargetPath: output
          prebuild_steps:
            - task: Bash@3
              displayName: Copy Nginx files to build folder
              inputs:
                targetType: "inline"
                script: |
                  cp -r $(Build.SourcesDirectory)/nginx $(Pipeline.Workspace)/dockerFiles

  - stage: updateHelmConfig
    displayName: Update Helm Config Repository
    dependsOn:
      - docker_publish
    jobs:
      - job: updateHelmConfigJob
        pool:
          name: Default
        workspace:
          clean: all
        steps:
          - template: step_collections/process-cicd-script/v1.yml@templates
            parameters:
              repositoryResource: helmfileconfig
              branchName: $(Build.SourceBranch)
              tagsCollection: unifi_client=$(build.buildnumber)
              commitMessage: Updated unifi_client to $(build.buildnumber)
