resources:
  repositories:
    - repository: templates
      type: BitBucket
      endpoint: "Bitbucket - spydersoft"
      name: spydersoftteam/azure-devops-templates
    - repository: helmfileconfig
      type: BitBucket
      endpoint: Bitbucket - spydersoft
      name: spydersoftteam/ha-helm-app-config

variables:
  #- group: confluence-credentials
  - name: CI
    value: true
  - name: artifactName
    value: unifi-client
  - name: dockerRepository
    value: spydersoft/ha/unifi.client
  - name: dockerServiceConnection
    value: proget_docker
  - name: branchTag
    ${{ if contains(variables['Build.SourceBranch'], 'main') }}:
      value: main
    ${{ if not(contains(variables['Build.SourceBranch'], 'main')) }}:
      value: feature

trigger:
  - main
pr: none

stages:
  - stage: build
    jobs:
      - job: buildJob
        pool:
          name: Default
        steps:
          - template: step_collections/npm-build-test.yml@templates
            parameters:
              artifactName: $(artifactName)
              runTests: false
              zipBuildArtifacts: true

  - stage: create_container_and_publish
    displayName: Create Container and Publish
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn: build
    jobs:
      - template: jobs/docker-image-build-job.yml
        parameters:
          dockerImageName: $(dockerRepository)
          containerRegistryName: proget_docker
          containerRegistryUrl: proget.mattgerega.com
          artifactName: $(artifactName)
          artifactZipName: $(artifactName)
          dockerImageFileName: unifi_client
  #     - job: update_ops_repo
  #       displayName: Update image version in Ops Repository
  #       workspace:
  #         clean: all
  #       dependsOn:
  #         - build_docker
  #       pool:
  #         name: "Scaled Pool - Ubuntu"
  #       steps:
  #         - template: publish/execute-cicd-script-in-repo/execute-cicd-script-in-repo-v1.yml@templates
  #           parameters:
  #             repositoryResource: gitops-repo
  #             appName: tech-debt-calculator
  #             additionalArguments: "$(branchTag)-$(build.buildnumber)"
  #             commitMessage: Updated tech-debt-calculator appVersion to $(branchTag)-$(build.buildnumber)
